---
title: "box_comparison"
author: "Celeste"
date: "2026-02-25"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}

library(tidyverse)
library(broom)
library(knitr)
library(dplyr)
```

## Load data

```{r}
# Combined data
combined <- read.csv("NPP_AMF_combined.csv")

# need to remove the fourth row bc I'm missing data (the bnpp)
combined <- combined[-4,]

combined <- combined %>%
  mutate(
    Inoculation = factor(Inoculation),
    Polyculture = factor(Polyculture),
    Group = interaction(Inoculation, Polyculture, sep = "_")
  )

# Speciality subsetted ones
mono_only <- combined[combined$Polyculture != "Inter", ]

inter_only <- combined[combined$Polyculture != "Mono", ]

```

# Basic stats analysis

## Berries

```{r}
# Berry stats
an_berry1 <- aov(Berries_g_pp~Polyculture+Inoculation+Water, data= combined)
summary(an_berry1)

an_berry2 <- aov(Berries_g_pp~Polyculture*Inoculation*Water, data= combined)
summary(an_berry2)

an_berry2.1 <- aov(Berries_g_pp~Polyculture*hyphal_colonization*Water, data= combined)
summary(an_berry2.1)

lm_berry2 <- lm(Berries_g_pp~Polyculture*Inoculation*Water, data= combined)
summary(lm_berry2)

an_berry2 <- aov(BNPP_g_pp~Polyculture, data= combined)
summary(an_berry2)


# % berries
an_percent_berries1 <- aov(percent_berries~Polyculture+Inoculation+Water, data= combined)
summary(an_percent_berries1)

an_percent_berries2 <- aov(percent_berries~Polyculture*Inoculation*Water, data= combined)
summary(an_percent_berries2)


an_percent_BNPP2 <- aov(percent_berries_of_wheat~Polyculture
                        #*Inoculation*Water
                        , data= combined)
summary(an_percent_BNPP2)

# to save
an_berry2_tidy <- tidy(an_berry2)
write.csv(an_berry2_tidy,
          file.path(("BasicANOVA"), "an_berry2.csv"),
          row.names = FALSE)

an_percent_berries2_tidy <- tidy(an_percent_berries2)
write.csv(an_percent_berries2_tidy,
          file.path(("BasicANOVA"), "an_percent_berries2.csv"),
          row.names = FALSE)



```

## ANPP

```{r}
# ANPP stats
an_ANPP1 <- aov(ANPP_g_pp~Polyculture+Inoculation+Water, data= combined)
summary(an_ANPP1)

an_ANPP2 <- aov(ANPP_g_pp~Polyculture*Inoculation*Water, data= combined)
summary(an_ANPP2)

lm_ANPP2 <- lm(ANPP_g_pp~Polyculture*Inoculation*Water, data= combined)
summary(lm_ANPP2)

# % anpp
an_percent_ANPP1 <- aov(percent_ANPP~Polyculture+Inoculation+Water, data= combined)
summary(an_percent_ANPP1)

an_percent_ANPP2 <- aov(percent_ANPP~Polyculture*Inoculation*Water, data= combined)
summary(an_percent_ANPP2)

an_percent_ANPP2 <- aov(percent_ANPP_of_wheat~Polyculture
                        #*Inoculation*Water
                        , data= combined)
summary(an_percent_ANPP2)

# to save
an_ANPP2_tidy <- tidy(an_ANPP2)
write.csv(an_ANPP2_tidy,
          file.path(("BasicANOVA"), "an_ANPP2.csv"),
          row.names = FALSE)

an_percent_ANPP2_tidy <- tidy(an_percent_ANPP2)
write.csv(an_percent_ANPP2_tidy,
          file.path(("BasicANOVA"), "an_percent_ANPP2.csv"),
          row.names = FALSE)

```

## BNPP

```{r}
# BNPP stats
an_BNPP1 <- aov(BNPP_g_pp~Polyculture+Inoculation+Water, data= combined)
summary(an_BNPP1)

an_BNPP2 <- aov(BNPP_g_pp~Polyculture*Inoculation*Water, data= combined)
summary(an_BNPP2)

lm_BNPP2 <- lm(BNPP_g_pp~Polyculture*Inoculation*Water, data= combined)
summary(lm_BNPP2)

# % bnpp
an_percent_BNPP1 <- aov(percent_BNPP~Polyculture+Inoculation+Water, data= combined)
summary(an_percent_BNPP1)

an_percent_BNPP2 <- aov(percent_BNPP_of_wheat~Polyculture
                        #*Inoculation*Water
                        , data= combined)
summary(an_percent_BNPP2)

an_percent_BNPP2 <- aov(percent_BNPP_of_wheat~Inoculation*Water, data= mono_only)
summary(an_percent_BNPP2)

# to save
an_BNPP2_tidy <- tidy(an_BNPP2)
write.csv(an_BNPP2_tidy,
          file.path(("BasicANOVA"), "an_BNPP2.csv"),
          row.names = FALSE)

an_percent_BNPP2_tidy <- tidy(an_percent_BNPP2)
write.csv(an_percent_BNPP2_tidy,
          file.path(("BasicANOVA"), "an_percent_BNPP2.csv"),
          row.names = FALSE)

## Curious about just within monoculture
BNPP_percent_mono_only <- aov(percent_BNPP~Water*Inoculation, 
                            data = filter(combined, Polyculture %in% c("Mono")))
summary(BNPP_percent_mono_only)


```
## AMF

```{r}
# AMF
# hyphal
an_hyphal <- aov(hyphal_colonization~Polyculture+Water, data= combined)
summary(an_hyphal)

an_hyphal2 <- aov(hyphal_colonization~Polyculture*Water_gal*Inoculation, data= combined)
summary(an_hyphal2)

lm_hyphal2 <- lm(hyphal_colonization~Polyculture*Water, data= combined)
summary(an_hyphal2)

# vesicles

an_vesiclel <- aov(arb_vesc_colonization~Polyculture+Water_gal, data= combined)
summary(an_vesiclel)

an_vesicle2 <- aov(arb_vesc_colonization~Polyculture*Water_gal*Inoculation, data= combined)
summary(an_vesicle2)

ln_vesicle2 <- lm(arb_vesc_colonization~Polyculture*Water, data= combined)
summary(ln_vesicle2)

# to save
an_hyphal_tidy <- tidy(an_hyphal2)
write.csv(an_hyphal_tidy,
          file.path(("BasicANOVA"), "an_hyphal2.csv"),
          row.names = FALSE)

an_vesicle2_tidy <- tidy(an_vesicle2)
write.csv(an_vesicle2_tidy,
          file.path(("BasicANOVA"), "an_vesicle2.csv"),
          row.names = FALSE)

```

## AMF

```{r}

an_AMF_hyphal <- aov(percent_ANPP~Polyculture*hyphal_colonization*Water, data= combined)
summary(an_AMF_hyphal)

an_AMF_vesicular <- aov(percent_ANPP~Polyculture*arb_vesc_colonization*Water, data= combined)
summary(an_AMF_vesicular)

```

## Fava

```{r}

fava_subset <- combined %>%
  filter(Polyculture == "Inter")

# biomass
an_fava1 <- aov(Fava_g~Inoculation+Water_gal, data= fava_subset)
summary(an_fava1)

an_fava2 <- aov(Fava_g~Inoculation*Water, data= fava_subset)
summary(an_fava2)

lm_fava2 <- lm(Fava_g~Inoculation*Water, data= fava_subset)
summary(lm_fava2)


# percent
an_percent_fava1 <- aov(percent_fava~Inoculation+Water_gal, data= fava_subset)
summary(an_percent_fava1)

an_percent_fava2 <- aov(percent_fava~Inoculation*Water, data= fava_subset)
summary(an_percent_fava2)

lm_percent_fava2 <- lm(percent_fava~Inoculation*Water, data= fava_subset)
summary(lm_percent_fava2)

```

## NPP All plants total pot productivity

```{r}
# all biomass stats
an_biomass1 <- aov(NPP_g_pp~Polyculture+Inoculation+Water, data= combined)
summary(an_biomass1)

an_biomass2 <- aov(NPP_g_pp~Polyculture*Inoculation*Water, data= combined)
summary(an_biomass2)

lm_biomass2 <- lm(NPP_g_pp~Polyculture*Inoculation*Water, data= combined)
summary(lm_biomass2)

## Curious about just within monoculture
an_biomass1_mono_only <- aov(NPP_g_pp~Inoculation+Water, data= filter(combined, Polyculture %in% c("Mono")))
summary(an_biomass1_mono_only)

an_biomass2_mono_only <- aov(NPP_g_pp~Inoculation*Water, data= filter(combined, Polyculture %in% c("Mono")))
summary(an_biomass2_mono_only)

```
# plot

```{r}
interaction_data <- combined %>%
  group_by(Polyculture, Inoculation) %>%
  summarise(
    mean_prod = mean(Pot_productivity, na.rm = TRUE),
    se_prod = sd(Pot_productivity, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )

ggplot(interaction_data,
       aes(x = Polyculture,
           y = mean_prod,
           color = Inoculation,
           group = Inoculation)) +
  geom_point(size = 3) +
  geom_line(linewidth = 1) +
  geom_errorbar(aes(ymin = mean_prod - se_prod,
                    ymax = mean_prod + se_prod),
                width = 0.1) +
  labs(
    title = "Interaction between Polyculture and Inoculation on Pot Productivity",
    x = "Polyculture Treatment",
    y = "Mean Pot Productivity"
  )
```


## NPP Wheat only

```{r}
# all biomass stats
an_wheat_NPP1 <- aov(Wheat_NPP_pp~Polyculture+Inoculation+Water, data= combined)
summary(an_wheat_NPP1)

an_biomass2 <- aov(NPP_g_pp~Polyculture*Inoculation*Water, data= combined)
summary(an_biomass2)

lm_biomass2 <- lm(NPP_g_pp~Polyculture*Inoculation*Water, data= combined)
summary(lm_biomass2)
```

