---
title: "SignificanceTable"
output: html_document
date: "2026-08-05"
---

This doc is to CLEAN UPP this code and try to generate a new, up to date significance table (stats + figs).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}

library(tidyverse)
library(broom)
library(knitr)
library(dplyr)
library(ggplot2)

# stats ones
library(car)
library(emmeans)
library(effectsize)
library(WRS2)
```

# 0. Load data

```{r}
# Combined data
# (path has one extra "../" vs. the original CleanCode/ location - this file
# now lives in CleanCode/PerPlant/, one folder deeper)
combined <- read.csv("../../Data/full_dataset.csv")

# need to remove the fourth row bc I'm missing data (the bnpp)
combined <- combined[-4,]

combined <- combined %>%
  mutate(
    Inoculation = factor(Inoculation),
    Polyculture = factor(Polyculture),
    Group = interaction(Inoculation, Polyculture, sep = "_")
  )
```

I'm going to go column by column on this doc (https://docs.google.com/document/d/1YjrffG9mcl9C2PJD0GSHFKL8UwIh1tsAJpzs35qtglc/edit?tab=t.4atnhr9xwxx0). 

I'm going to do mono and inter as two other docs.

# 1. Wheat ANPP

Using value: W_ANPP_g_pp

## 1.1 stats

### 1.1.1 Stats, basic interactions

```{r}
# ANOVA 3-way
anova_w_anpp_pp <- aov(W_ANPP_g_pp~Inoculation*Polyculture*Water, data= combined)
summary(anova_w_anpp_pp)

# ANOVA 2-way
anova_w_anpp_pp_2 <- aov(W_ANPP_g_pp~Polyculture*Water, data= combined)
summary(anova_w_anpp_pp_2)

# ANOVA amf
anova_w_anpp_pp_3 <- aov(W_ANPP_g_pp~hyphal_colonization*Polyculture*Water, data= combined)
summary(anova_w_anpp_pp_3)
```

# 1.2 stats assumption checking, basic interactions

```{r}

# Assumption checking
mod <- aov(W_ANPP_g_pp ~ Inoculation * Water, data = combined)
plot(mod, 2)  # QQ plot normality of residuals
shapiro.test(residuals(mod))
  #LOOKS GOOD

plot(mod, 1)  # residuals vs fitted
leveneTest(W_ANPP_g_pp ~ interaction(Inoculation, Water), data = combined)

# Post-hoc tests
emmeans(mod, pairwise ~ Water, adjust = "tukey")

# Effect sizes
eta_squared(mod)

# r squared
mod_lm <- lm(W_ANPP_g_pp ~ Inoculation * Water, data = combined)
summary(mod_lm)


# cleanly together
mod <- lm(W_ANPP_g_pp ~ Inoculation * Water, data = combined)

summary(mod)        # gives R²
anova(mod)  

# okay type 2 anova??
mod <- lm(W_ANPP_g_pp ~ Inoculation * Water, data = combined)

Anova(mod, type = 2)   # correct ANOVA
summary(mod)$r.squared # R²
```


# 1.3 figs

```{r}
# ANPP x polyculture
ggplot(combined, aes(x = Polyculture, y = W_ANPP_g_pp)) +
  stat_summary(fun = mean, geom = "bar") +
  labs(title = "Polyculture impact on ANPP (treatment means)", x = "", y = "ANPP per plant (g)")

# ANPP x Inoculation
ggplot(combined, aes(x = Inoculation, y = W_ANPP_g_pp)) +
  stat_summary(fun = mean, geom = "bar") +
  labs(title = "Inoculation impact on ANPP (treatment means)", x = "", y = "ANPP per plant (g)")

# ANPP x polyculture
ggplot(combined, aes(x = hyphal_colonization, y = W_ANPP_g_pp)) +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Polyculture impact on ANPP (treatment means)", x = "", y = "ANPP per plant (g)")

# ANPP x PPT
ggplot(combined, aes(x = Water, y = W_ANPP_g_pp)) +
  stat_summary(fun = mean, geom = "bar") +
  labs(title = "Water impact on ANPP", x = "", y = "ANPP per plant (g)")

```
