---
title: "big_takeaways"
output: html_document
---

This doc is just to look at figures that could help me with my big takeaways (or what I think they are so far..?)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}

library(tidyverse)
library(broom)
library(knitr)
library(dplyr)
library(ggplot2)
```

## Load data

```{r}
# Combined data
combined <- read.csv("../Cross_compare/NPP_AMF_combined.csv")

# need to remove the fourth row bc I'm missing data (the bnpp)
combined <- combined[-4,]

combined <- combined %>%
  mutate(
    Inoculation = factor(Inoculation),
    Polyculture = factor(Polyculture),
    Group = interaction(Inoculation, Polyculture, sep = "_")
  )

# new column which is wheat NPP
combined <- combined %>%
  rowwise() %>%
  mutate(Wheat_NPP = sum(c(ANPP_g_pp,BNPP_g_pp,Berries_g_pp))) %>%
  ungroup()

# new column which is wheat as percentage of NPP
combined <- combined %>%
  rowwise() %>%
  mutate(percent_wheat_NPP = (Wheat_NPP/NPP_g_pp)) %>%
  ungroup()

# Speciality subsetted ones
mono_only <- combined[combined$Polyculture != "Inter", ]

inter_only <- combined[combined$Polyculture != "Mono", ]

```

## Part 1: Monoculture story

For NPP, inoculation and water are both significant

```{r}
# NPP

# Check stat significance
an_biomass2_mono_only <- aov(NPP_g_pp~Inoculation*Water, data= mono_only)
summary(an_biomass2_mono_only)

# Water: Inoc interaction
ggplot(mono_only, aes(x = Water, y = NPP_g_pp, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Mono Only: Water:Inoculation Interaction Impacts on system NPP", x = "", y = "NPP")

# Berries

##  Total berries
# Stats
an_berries2_mono_only <- aov(Berries_g_pp~Inoculation*Water, data= mono_only)
summary(an_berries2_mono_only)

# Water: Inoc interaction
ggplot(mono_only, aes(x = Water, y = Berries_g_pp, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Mono Only: Water:Inoculation Interaction Impacts on Berry Productivity", x = "", y = "NPP")

## Percent berries
# Stats
an_berries_percent2_mono_only <- aov(percent_berries~Inoculation*Water, data= mono_only)
summary(an_berries_percent2_mono_only)

# Water: Inoc interaction
ggplot(mono_only, aes(x = Water, y = percent_berries, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Mono Only: Water:Inoculation Interaction Impacts on Allocation to Berries", x = "", y = "% berries")

## BNPP
# Water: Inoc interaction
ggplot(mono_only, aes(x = Water, y = percent_BNPP, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Mono Only: Water:Inoculation Interaction Impacts on Allocation to BNPP", x = "", y = "% BNPP")

## ANPP
# Water: Inoc interaction
ggplot(mono_only, aes(x = Water, y = percent_ANPP, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Mono Only: Water:Inoculation Interaction Impacts on Allocation to ANPP", x = "", y = "% ANPP")

```

## Part 2: Intercropping only, what is fava doing?

```{r}

# NPP including fava
# Check stat significance
an_biomass2_mono_only <- aov(NPP_g_pp~Inoculation*Water, data= inter_only)
summary(an_biomass2_mono_only)

# Water: Inoc interaction
ggplot(inter_only, aes(x = Water, y = NPP_g_pp, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Inter Only: Water:Inoculation Interaction Impacts on system NPP", x = "", y = "NPP")

#FAVA productivity
# Water: Inoc interaction
ggplot(inter_only, aes(x = Water, y = Fava_g, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Water:Inoculation Interaction Impacts on fava productivity", x = "", y = "Fava (g)")

#FAVA percent
# Water: Inoc interaction
ggplot(inter_only, aes(x = Water, y = percent_fava, color = Inoculation, 
                       group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Water:Inoculation Interaction Impacts on allocation to fava", x = "", y = "Fava %")


# Wheat NPP combined
# Water: Inoc interaction
ggplot(inter_only, aes(x = Water, y = Wheat_NPP, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Water:Inoculation Interaction Impacts on wheat (combined) productivity", x = "", y = "Wheat NPP (g)")

an_wheatNPP2_inter_only <- aov(Wheat_NPP~Inoculation*Water, data= mono_only)
summary(an_wheatNPP2_inter_only)

# Wheat NPP combined %
# Water: Inoc interaction
ggplot(inter_only, aes(x = Water, y = percent_wheat_NPP, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Water:Inoculation Interaction Impacts on wheat (combined) productivity", x = "", y = "Wheat NPP (g)")

an_wheatNPP_percent_inter_only <- aov(percent_wheat_NPP~Inoculation*Water, data= mono_only)
summary(an_wheatNPP_percent_inter_only)


## How is this happening? Which specific parts of wheat are losing out

# BERRIES
# Percent
ggplot(inter_only, aes(x = Water, y = percent_berries, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Water:Inoculation Interaction Impacts on allocation to berries", x = "", y = "Berry %")

an_berries_percent_inter_only <- aov(percent_berries~Inoculation*Water, data= mono_only)
summary(an_berries_percent_inter_only)

# total
  # not interesting
ggplot(inter_only, aes(x = Water, y = Berries_g_pp, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Water:Inoculation Interaction Impacts on Berry (g)", x = "", y = "Berry g")

# ANPP
# Percent
ggplot(inter_only, aes(x = Water, y = percent_ANPP, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Water:Inoculation Interaction Impacts on allocation to ANPP", x = "", y = "ANPP %")

an_ANPP_percent_inter_only <- aov(percent_ANPP~Inoculation*Water, data= mono_only)
summary(an_ANPP_percent_inter_only)

# total
ggplot(inter_only, aes(x = Water, y = ANPP_g_pp, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Water:Inoculation Interaction Impacts on ANPP (g)", x = "", y = "ANPP g")

# BNPP
# Percent
ggplot(inter_only, aes(x = Water, y = percent_BNPP, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Water:Inoculation Interaction Impacts on allocation to BNPP", x = "", y = "BNPP %")

# total
  # not interesting
ggplot(inter_only, aes(x = Water, y = BNPP_g_pp, color = Inoculation, group = Inoculation)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun = mean, geom = "line") +
  labs(title = "Water:Inoculation Interaction Impacts on BNPP (g)", x = "", y = "BNPP g")

an_BNPP_percent_inter_only <- aov(percent_BNPP~Inoculation*Water, data= mono_only)
summary(an_BNPP_percent_inter_only)

```

